name: web E2E tests

on:
  workflow_dispatch:

jobs:
  web-tests:

    runs-on: ubuntun-latest

    steps:
    
      # clone do projeto para a máquina
      - uses: actions/checkout@v4

      # Conferir a versao instalada
      - name: Node version
        run: Node --version

      - name: instalando dependencias
        run: npm install

      - name: executando os testes
        run: npx cypress run

      - uses: actions/upload-artifact@v4  
        if: ${{ !cancelled() }}
        with:
          name: relatorios
          path:
            cypress/reports
            cypress/screenshots
            cypress/videos
        

         

        
      
 
